#!/system/bin/sh

FILE=/data/data/com.netflix.mediaclient/shared_prefs/nfxpref.xml
[ -f $FILE ] && sed -i '/name=\"nflx_player_type\"/d;s|</map>|    <int name="nflx_player_type" value="10" />\n</map>|g' $FILE
